package vn.inventoryai.common.error;

public enum ErrorCode {
    UNAUTHORIZED,
    FORBIDDEN,
    VALIDATION_ERROR,
    NOT_FOUND,
    EMAIL_ALREADY_EXISTS,
    BAD_CREDENTIALS,
    USER_DISABLED,
    MUST_CHANGE_PASSWORD,
    STORE_MISMATCH,
    PLAN_LIMIT_EXCEEDED,
    IDEMPOTENCY_CONFLICT,
    PAYMENT_PROVIDER_ERROR,
    PAYMENT_REVIEW_REQUIRED,
    PAYMENT_SIGNATURE_INVALID,
    PAYMENT_AMOUNT_MISMATCH,
    INSUFFICIENT_STOCK,
    INGREDIENT_CODE_ALREADY_EXISTS,
    INGREDIENT_HAS_STOCK,
    TOKEN_INVALID,
    INTERNAL_ERROR,
    EMAIL_DELIVERY_UNAVAILABLE,
    RATE_LIMITED
}
