package vn.inventoryai.subscription;

import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.*;
import vn.inventoryai.common.error.AppException;
import vn.inventoryai.common.error.ErrorCode;
import vn.inventoryai.subscription.dto.PaymentWebhookRequest;
import vn.inventoryai.subscription.dto.PaymentWebhookResponse;
import vn.inventoryai.subscription.payment.PaymentGatewayRegistry;

import java.util.Map;

@RestController
@RequestMapping("/api/webhook/payment")
@RequiredArgsConstructor
public class PaymentWebhookController {
    private final SubscriptionService subscriptionService;
    private final PaymentGatewayRegistry paymentGatewayRegistry;

    @PostMapping("/payos")
    PaymentWebhookResponse payOsWebhook(@RequestBody Map<String, Object> webhook) {
        Map<String, Object> data = nestedData(webhook.get("data"));
        boolean success = Boolean.TRUE.equals(webhook.get("success"))
                && "00".equals(String.valueOf(webhook.get("code")))
                && "00".equals(String.valueOf(data.get("code")));
        PaymentWebhookRequest request = new PaymentWebhookRequest(
                String.valueOf(data.get("orderCode")),
                success ? PaymentStatus.SUCCESS : PaymentStatus.FAILED,
                webhook.get("signature") == null ? null : String.valueOf(webhook.get("signature")),
                success ? null : String.valueOf(data.get("desc")),
                webhook
        );
        // payOS sends a signed sample with orderCode=123 when validating a webhook URL.
        // Real order codes generated by this application are 16 digits.
        if ("123".equals(request.providerTransactionId())) {
            if (!paymentGatewayRegistry.get("PAYOS").verifyWebhook(request)) {
                throw new AppException(ErrorCode.PAYMENT_SIGNATURE_INVALID, HttpStatus.FORBIDDEN, "Invalid payOS webhook signature");
            }
            return new PaymentWebhookResponse(null, request.status(), false);
        }
        return subscriptionService.handleWebhook("PAYOS", request);
    }

    @SuppressWarnings("unchecked")
    private Map<String, Object> nestedData(Object value) {
        return value instanceof Map<?, ?> map ? (Map<String, Object>) map : Map.of();
    }
}
